import type { AppExtensions as HarnessyEngineAppExtensions } from "@executor-js/api/server";

export {
	type AppConfig,
	type AppExtensions,
	type AppProviders,
	AuthContext,
	authContextFromPrincipal,
	type CodeExecutor,
	CodeExecutorProvider,
	type CommonProviders,
	type CreateExecutorFumaDbOptions,
	consoleErrorCapture,
	createExecutorFumaDb,
	DbProvider,
	dbProviderLayer,
	EngineDecorator,
	EngineDecoratorNoop,
	type EngineDecoratorShape,
	type EngineProviders,
	ExecutorApp,
	type ExecutorAppOptions,
	type ExecutorDbHandle,
	type ExecutorDbProvider,
	type ExecutorFumaDb,
	type ExecutorFumaSchema,
	type FixedExecutionProviders,
	HostConfig,
	type HostConfigShape,
	type IdentityFailure,
	IdentityProvider,
	type IdentityProviderShape,
	type McpProviders,
	NoOrganization,
	PluginsProvider,
	type PluginsProviderShape,
	type Principal,
	type ScopedExecutionProviders,
	textFailureStrategy,
	Unauthorized,
	Unavailable,
} from "@executor-js/api/server";
export { Context, Data, Effect, Layer, Option, Schema } from "effect";

export type HarnessyEngineRouteExtension = NonNullable<HarnessyEngineAppExtensions["routes"]>[number];

export {
	type AuthOutcome,
	authenticated,
	defaultMcpResource,
	forbidden,
	type McpAuthenticated,
	McpAuthProvider,
	type McpDiscoveryRoute,
	type McpDispatchInput,
	type McpDispatchResult,
	McpErrorReporter,
	type McpForbidden,
	type McpResource,
	McpSessionStore,
	type McpUnauthorized,
	type McpUnavailable,
	mcpResourceKey,
	principalOwns,
	unauthorized,
	unavailable,
} from "@executor-js/host-mcp";

export {
	type CreateToolPolicyInput,
	type EffectivePolicy,
	effectivePolicyFromSorted,
	isValidPattern,
	matchPattern,
	type PolicyMatch,
	type PolicySource,
	type RemoveToolPolicyInput,
	type ToolPolicy,
	ToolPolicyActionSchema,
	type UpdateToolPolicyInput,
} from "@executor-js/sdk";
